import numpy as m
import matplotlib.pyplot as plt
x1=m.arange(-20,20,.05)
x2=m.arange(2,20,.02)
y1=x1**2
y2=m.cos(x2)
plt.plot(x1,y1,'*--')
plt.show()
plt.plot(x2,y2,'ro--')
plt.grid()
plt.show()
plt.plot(x2,y2,'bo--')
plt.show()
plt.plot(x1,y1,'o-',markersize=4.25,color='red')
plt.show()
plt.plot(x1,y1,'H-',markersize=2.25,color='yellow')
plt.show()
plt.plot(x1,y1,'d-',markersize=2.25,color='purple')
plt.show()
plt.title('Graph of square function')
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid()
plt.show()

plt.plot(x1,y1,'d-',markersize=2.25,color='purple')
plt.show()
plt.title('Graph of square function')
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.show()

plt.title('Graph of Cube function')
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid()
plt.show()
x=m.arange(-20,10,1)
y1=(14-2*x)/3
y2=(x-12)/7
plt.plot(x,y1,'bo-',markersize=5.5,color='b')
plt.title('Graph of two lines')
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid()
plt.show()
plt.plot(x,y2,'*-',markersize=25.5,color='g')
plt.show()